"""add scheme_id to portfolios

Revision ID: 45ebeb0823c4
Revises: 7e4492870116
Create Date: 2026-06-29 21:28:17.062511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ebeb0823c4'
down_revision: Union[str, None] = '7e4492870116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('scheme_id', sa.String(length=64), nullable=False,server_default='dark'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'scheme_id')
    # ### end Alembic commands ###
