"""make email nullable

Revision ID: bd949a331627
Revises: 101b791bf62f
Create Date: 2026-06-16 17:38:47.332267

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd949a331627'
down_revision: str | None = '101b791bf62f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    # ### end Alembic commands ###
