"""add accent to portfolios

Revision ID: f6004a57c7f8
Revises: 45ebeb0823c4
Create Date: 2026-07-04 13:35:48.643981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6004a57c7f8'
down_revision: Union[str, None] = '45ebeb0823c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('accent', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'accent')
    # ### end Alembic commands ###
